[program:laravel-horizon-wholesale-paint-group]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/wholesale-paint-group/artisan horizon
autostart=true
autorestart=true
redirect_stderr=true
user=laradock
stdout_logfile=/var/www/wholesale-paint-group/storage/logs/horizon.log
